### ISSUE TITLE
checkhealth

### ISSUE THREAD

**Issue by mimikun** [mimikun/nvim-mason-v2#4]
- [ ] blink-cmp-dictionary
- [ ] conform           
- [ ] diffview          
- [ ] dressing          
- [ ] mason            
- [ ] mcphub            
- [ ] neoconf           
- [ ] noice             
- [ ] render-markdown   
- [ ] rustaceanvim      
- [ ] snacks            
- [ ] vim.lsp           
- [ ] which-key

**Comment by mimikun** [comment]
### conform: 2 ⚠️

```

==============================================================================

conform.nvim report ~
- Log file: /home/mimikun/.local/state/nvim/conform.log
- ✅ OK fish_indent ready (fish)
- ⚠️ WARNING nixfmt unavailable: Command 'nixfmt' not found
- ✅ OK prettier ready (json, less, flow, yaml, vue, scss, html, markdown, jsonc, graphql, htmlangular, htmldjango, css, svelte, javascript, javascriptreact, typescript, typescriptreact, astro)
- ✅ OK shfmt ready (sh)
- ✅ OK stylua ready (lua, luau)
- ⚠️ WARNING textlint unavailable: Command 'textlint' not found

```

**Comment by mimikun** [comment]
### diffview: 1 ⚠️

```

==============================================================================
diffview:                                                                 1 ⚠️

Checking plugin dependencies ~
- ✅ OK nvim-web-devicons installed.

Checking VCS tools ~
- The plugin requires at least one of the supported VCS tools to be valid.
- ✅ OK Git found.
- ✅ OK Git is up-to-date. (2.43.0)
- ⚠️ WARNING Configured `hg_cmd` is not executable: 'hg'

```

**Comment by mimikun** [comment]
#### dressing: 1 ⚠️

```

==============================================================================
dressing:                                                                 1 ⚠️

dressing.nvim ~
- ⚠️ WARNING vim.ui.input not enabled
- ✅ OK vim.ui.select active: telescope


```

**Comment by mimikun** [comment]
### mason: 5 ⚠️

```
==============================================================================


mason.nvim ~
- ✅ OK mason.nvim version v2.0.0
- ✅ OK PATH: prepend
- ✅ OK Providers: 
    mason.providers.registry-api
    mason.providers.client
- ✅ OK neovim version >= 0.10.0

mason.nvim [Registries] ~
- ✅ OK Registry `github.com/crashdummyy/mason-registry version: 2025-05-16-single-house` is installed.
- ✅ OK Registry `github.com/mimikun/mason-registry version: 2025-02-05-wobbly-phoenix` is installed.
- ✅ OK Registry `github.com/mkindberg/ghostty-ls version: v0.0.5` is installed.
- ✅ OK Registry `github.com/mason-org/mason-registry version: 2025-05-16-dynamic-soccer` is installed.

mason.nvim [Core utils] ~
- ✅ OK unzip: `UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.`
- ✅ OK wget: `GNU Wget 1.21.4 built on linux-gnu.`
- ✅ OK curl: `curl 8.5.0 (x86_64-pc-linux-gnu) libcurl/8.5.0 OpenSSL/3.0.13 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.7 libpsl/0.21.2 (+libidn2/2.3.7) libssh/0.10.6/openssl/zlib nghttp2/1.59.0 librtmp/2.3 OpenLDAP/2.6.7`
- ✅ OK gzip: `gzip 1.12`
- ✅ OK tar: `tar (GNU tar) 1.35`
- ✅ OK bash: `GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)`
- ✅ OK sh: `Ok`

mason.nvim [Languages] ~
- ✅ OK Ruby: `ruby 3.4.4 (2025-05-14 revision a38531fd3f) +PRISM [x86_64-linux]`
- ⚠️ WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. Could not find executable "composer" in PATH.

- ⚠️ WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. Could not find executable "php" in PATH.

- ✅ OK RubyGem: `3.6.7`
- ✅ OK luarocks: `/home/mimikun/.local/share/mise/installs/lua/5.1/luarocks/bin/luarocks 3.11.1`
- ⚠️ WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code - and signal -. Could not find executable "javac" in PATH.

- ⚠️ WARNING java: not available
  - ADVICE:
    - spawn: java failed with exit code - and signal -. Could not find executable "java" in PATH.

- ⚠️ WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. Could not find executable "julia" in PATH.

- ✅ OK cargo: `cargo 1.89.0-nightly (056f5f4f3 2025-05-09)`
- ✅ OK Go: `go version go1.24.3 linux/amd64`
- ✅ OK python: `Python 3.13.3`
- ✅ OK node: `v22.15.1`
- ✅ OK npm: `10.9.2`
- ✅ OK pip: `pip 24.3.1 from /home/mimikun/.local/share/mise/installs/python/3.13.3/lib/python3.13/site-packages/pip (python 3.13)`
- ✅ OK python venv: `Ok`
```
